### ISSUE TITLE
HA 2023.08 업데이트 후 동작하지 않습니다.

### ISSUE THREAD

**Issue by Murianwind** [miumida/naver_weather#16]
Logger: homeassistant.components.weather
Source: helpers/entity_platform.py:619
Integration: 날씨 (documentation, issues)
First occurred: 07:02:42 (2 occurrences)
Last logged: 07:02:42

Error adding entities for domain weather with platform naver_weather
Error while setting up naver_weather platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'DeviceEntryType'

=====

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:619
Integration: 센서 (documentation, issues)
First occurred: 07:02:42 (6 occurrences)
Last logged: 07:02:43

Error adding entities for domain sensor with platform naver_weather
Error while setting up naver_weather platform for sensor
Error adding entities for domain sensor with platform mart_holiday
Error while setting up mart_holiday platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'DeviceEntryType'

**Comment by Murianwind** [comment]
업데이트해주셔서 감사합니다. 더운 여름 날씨 항상 건강하세요.
