### ISSUE TITLE
네이버 날씨를 불러오지 못하고 있습니다.

### ISSUE THREAD

**Issue by Murianwind** [miumida/naver_weather#19]
11월 30일 오후 3시 이후 네이버 날씨가 데이터를 불러오지 못하고 있습니다.

이 오류는 사용자 통합구성요소에서 발생했습니다.

Logger: custom_components.naver_weather.api_nweather
Source: custom_components/naver_weather/api_nweather.py:229
Integration: 네이버 날씨 (documentation)
First occurred: 02:21:58 (1 occurrences)
Last logged: 02:21:58

Failed to update NWeather API NowTemp Error : 'NoneType' object has no attribute 'text'

이 오류는 사용자 통합구성요소에서 발생했습니다.

Logger: custom_components.naver_weather.api_nweather
Source: custom_components/naver_weather/api_nweather.py:265
Integration: 네이버 날씨 (documentation)
First occurred: 02:21:58 (1 occurrences)
Last logged: 02:21:58

Failed to update NWeather API WeatherCast Error : 'NoneType' object has no attribute 'select_one'

이 오류는 사용자 통합구성요소에서 발생했습니다.

Logger: custom_components.naver_weather.api_nweather
Source: custom_components/naver_weather/api_nweather.py:571
Integration: 네이버 날씨 (documentation)
First occurred: 02:21:59 (1 occurrences)
Last logged: 02:21:59

Failed to update NWeather API status Error: list index out of range

Logger: homeassistant.components.weather
Source: helpers/entity_platform.py:507
Integration: 날씨 (documentation, issues)
First occurred: 02:21:59 (1 occurrences)
Last logged: 02:21:59

Error adding entities for domain weather with platform naver_weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1022, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/naver_weather/nweather_device.py", line 69, in async_added_to_hass
    await self.api.update()
  File "/config/custom_components/naver_weather/api_nweather.py", line 353, in update
    condition_main = soup.select("section.sc_new.cs_weather_new._cs_weather > div._tab_flicking > div.content_wrap > div.open > div > div > div.weather_info > div > div > div.weather_graphic > div.weather_main > i.wt_icon")[0]["class"][1]
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range


Logger: homeassistant.components.weather
Source: helpers/entity_platform.py:367
Integration: 날씨 (documentation, issues)
First occurred: 02:21:59 (1 occurrences)
Last logged: 02:21:59

Error while setting up naver_weather platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1022, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/naver_weather/nweather_device.py", line 69, in async_added_to_hass
    await self.api.update()
  File "/config/custom_components/naver_weather/api_nweather.py", line 353, in update
    condition_main = soup.select("section.sc_new.cs_weather_new._cs_weather > div._tab_flicking > div.content_wrap > div.open > div > div > div.weather_info > div > div > div.weather_graphic > div.weather_main > i.wt_icon")[0]["class"][1]
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range


Home Assistant

Core
2023.11.3
Supervisor
2023.11.6
Operating System
11.1
프론트엔드
20231030.2

**Comment by Murianwind** [comment]
감사합니다!!!

2023년 12월 1일 (금) 23:37, miumida ***@***.***>님이 작성:
